// <auto-generated />

using System;
using System.Collections.Generic;

namespace MultiTenant.Demo.TenantCore.Context
{
    #pragma warning disable 1591
    public partial class Summary
    {
        public Summary()
        {
            Weathers = new HashSet<Weather>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Weather> Weathers { get; set; }
    }
}
