// <auto-generated />

using System;
using System.Collections.Generic;

namespace MultiTenant.Demo.TenantCore.Context
{
    #pragma warning disable 1591
    public partial class Weather
    {
        public Guid Id { get; set; }
        public Guid SummaryId { get; set; }
        public string Tenant { get; set; }
        public DateTimeOffset Date { get; set; }
        public int TemperatureC { get; set; }

        public virtual Summary Summary { get; set; }
    }
}
